name: CD - Release on Tag

on:

  push:
    branches:
      - main
    # tags:
    #   - 'v*'

jobs:

  release:

    runs-on: ubuntu-latest

    env:

      CI: false

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Fetch tags
        run: git fetch --tags

      - name: Get the last tag and increment
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          
          VERSION_PARTS=(${LAST_TAG//./ })
          MAJOR=${VERSION_PARTS[0]#v}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          NEW_PATCH=$((PATCH + 1))
          
          TAG_NAME="v${MAJOR}.${MINOR}.${NEW_PATCH}"
          
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies & Build
        run: npm ci

      # - name: Publish NPM Package
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Generate Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true