name: CD - Create Tag on Main Merge

on:

  push:
    branches:
      - main

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Increment version & push tag
        run: |
          NEW_TAG=$(npm version patch)
          echo "New tag created: $NEW_TAG"
          git push origin main --follow-tags

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies & Build
        run: npm ci

      # - name: Publish NPM Package
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Generate Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true